// The one place an auth email is built, for both surfaces that render one.
//
//   supabase/templates/*.html   Go templates. They serve the local stack (captured by Mailpit)
//                               and are what you paste into Dashboard, Auth, Emails on the
//                               hosted project. Generated by scripts/build-email-templates.ts.
//   supabase/functions/send-email/index.ts
//                               The Send Email hook. When it is enabled GoTrue calls it
//                               INSTEAD of its own templating, and the dashboard editor goes
//                               dead. This is the production path when the hook is on.
//
// Nothing here branches on "am I building a template". The token-bearing values are just
// parameters: pass the Go placeholders and you get a Go template, pass real values and you get
// a finished message. That is why one module can own both surfaces without them drifting,
// and scripts/check-email-templates.ts fails the build if the committed files stop matching.
//
// This file must stay importable by BOTH Deno and tsx: no Deno.*, no node:*, no npm:, no I/O.

import { type CopyVars, copyFor, type EmailKind } from "./copy.ts";
import {
    confirmUrl,
    renderShell,
    renderText,
    sanitizeText,
    type ShellParts,
    subjectLine,
} from "./shell.ts";

export type { EmailKind, CopyVars };
export { EMAIL_KINDS } from "./copy.ts";
export { esc, LOGO_PATH, sanitizeText } from "./shell.ts";

/** Matches the 80-character cap ensembleSettingsInput.ts already applies to an ensemble name. */
const MAX_NAME = 80;
/** Long enough for "Your seat with <80 chars> is ready" without a runaway header line. */
const MAX_SUBJECT = 120;

/** The placeholders GoTrue's Go templates expand. Passing these through renderAuthEmail is what
 *  turns it into a template generator. */
export const GO = {
    siteUrl: "{{ .SiteURL }}",
    tokenHash: "{{ .TokenHash }}",
    email: "{{ .Email }}",
    newEmail: "{{ .NewEmail }}",
} as const;

export interface GoTemplate {
    kind: EmailKind;
    /** File under supabase/templates/. */
    file: string;
    /** The [auth.email.template.<key>] block in supabase/config.toml that wires it. */
    configKey: string;
}

/** The five Go templates, and the config blocks that must point at them. check-email-templates
 *  asserts this list against both the directory and config.toml, so an orphan file or an
 *  unwired template fails the build. */
export const GO_TEMPLATES: readonly GoTemplate[] = [
    { kind: "invite_shared", file: "invite.html", configKey: "invite" },
    { kind: "magiclink", file: "magic_link.html", configKey: "magic_link" },
    { kind: "recovery", file: "recovery.html", configKey: "recovery" },
    { kind: "signup", file: "confirmation.html", configKey: "confirmation" },
    {
        kind: "email_change_shared",
        file: "email_change.html",
        configKey: "email_change",
    },
];

/** Render one Go template: GoTrue's placeholders in place of real values. Only email_change
 *  interpolates addresses, and it names both, because GoTrue renders that one template for the
 *  current and the new address alike. Used by the build script and by the drift check, so both
 *  produce byte-identical output from the same call. */
export function renderGoTemplate(kind: EmailKind): RenderedEmail {
    return renderAuthEmail(kind, {
        siteUrl: GO.siteUrl,
        tokenHash: GO.tokenHash,
        ...(kind === "email_change_shared"
            ? { currentEmail: GO.email, nextEmail: GO.newEmail }
            : {}),
    });
}

export interface RenderOpts extends CopyVars {
    /** The app origin. '{{ .SiteURL }}' for the Go surface, email_data.site_url for the hook. */
    siteUrl: string;
    /** '{{ .TokenHash }}' for the Go surface, the real one-time hash for the hook. */
    tokenHash: string;
}

export interface RenderedEmail {
    subject: string;
    html: string;
    text: string;
}

export function renderAuthEmail(
    kind: EmailKind,
    opts: RenderOpts,
): RenderedEmail {
    // Cap and flatten every interpolated value before it reaches the copy. An ensemble name is
    // free-form text a director types, so it is the untrusted input on this path; the subject
    // is the context where a stray CR or LF would matter most.
    const vars: CopyVars = {
        ensembleName: clip(opts.ensembleName),
        invitedByName: clip(opts.invitedByName),
        displayName: clip(opts.displayName),
        currentEmail: clip(opts.currentEmail),
        nextEmail: clip(opts.nextEmail),
        dualConfirm: opts.dualConfirm,
    };

    const copy = copyFor(kind, vars);
    const parts: ShellParts = {
        subject: subjectLine(copy.subject, MAX_SUBJECT),
        preheader: copy.preheader,
        eyebrow: copy.eyebrow,
        heading: copy.heading,
        body: copy.body,
        panel: copy.panel,
        button: copy.button,
        buttonUrl: confirmUrl(opts.siteUrl, opts.tokenHash, copy.linkType),
        finePrint: copy.finePrint,
        expiry: copy.expiry,
        siteUrl: opts.siteUrl,
    };

    return {
        subject: parts.subject,
        html: renderShell(parts),
        text: renderText(parts),
    };
}

function clip(value: string | undefined): string | undefined {
    if (value === undefined) return undefined;
    const flat = sanitizeText(value, MAX_NAME);
    return flat.length ? flat : undefined;
}

// ---------------------------------------------------------------------------
// The hook surface
// ---------------------------------------------------------------------------

/** The Send Email hook payload. Modelled on Supabase's published JSON Schema, narrowed to the
 *  fields this function reads. `new_email` is absent from that schema but present at runtime
 *  (GoTrue's models.User carries `EmailChange string \`json:"new_email,omitempty"\``), so it is
 *  optional here and every path that needs it checks. */
export interface HookEmailData {
    token: string;
    token_hash: string;
    redirect_to: string;
    email_action_type: string;
    site_url: string;
    token_new?: string;
    token_hash_new?: string;
    old_email?: string;
}

export interface HookUser {
    email: string;
    new_email?: string;
    user_metadata?: Record<string, unknown>;
}

export interface HookPayload {
    user: HookUser;
    email_data: HookEmailData;
}

export interface OutboundMessage {
    to: string;
    subject: string;
    html: string;
    text: string;
}

/** Either a complete send plan, or a refusal. Never a partial plan: a half-executed email
 *  change is the failure mode worth refusing over. */
export type HookPlan =
    | { ok: true; messages: OutboundMessage[] }
    | { ok: false; reason: string };

/** The action types this function renders. Everything else returns an empty plan rather than
 *  falling through to a sign-in link.
 *
 *  That fallthrough is what the previous version did, and it mattered: GoTrue's enum also
 *  carries `reauthentication` and six *_notification types. A password_changed_notification
 *  routed to "Your sign-in link" would reach the user as a broken link at
 *  /auth/confirm?token_hash=&type=password_changed_notification, which lands on
 *  /auth/auth-error. That destroys the notification's security value. None of those are
 *  enabled today (config.toml carries only a commented password_changed block, and nothing in
 *  apps/web calls reauthenticate), so an empty plan is correct and a warning is enough. */
const HANDLED = new Set([
    "invite",
    "magiclink",
    "recovery",
    "signup",
    "email_change",
]);

export function isHandledActionType(type: string): boolean {
    return HANDLED.has(type);
}

/** Turn one hook call into the messages it should send.
 *
 *  Most types are one message. email_change is not: GoTrue fires the hook ONCE and expects two
 *  emails, with the token pairs crossed. That branch is deliberately not wired yet, see below. */
/** The app origin to build links against.
 *
 *  NOT email_data.site_url. In a hook payload that field is GoTrue's OWN external URL, which on a
 *  hosted project is https://<ref>.supabase.co/auth/v1. Building against it produced
 *  https://<ref>.supabase.co/auth/v1/auth/confirm?token_hash=..., which the API gateway answers
 *  with "No API key found in request". redirect_to is the field that carries where the user should
 *  land, and GoTrue fills it from the project's Site URL when the caller passes none.
 *
 *  Only the origin: a caller may pass a redirectTo with a path, and every link built here appends
 *  its own. site_url is kept as a last resort so a payload without redirect_to still sends
 *  something, which is how the local Go-template surface has always behaved.
 */
function appOrigin(email_data: HookEmailData): string {
    for (const candidate of [email_data.redirect_to, email_data.site_url]) {
        if (!candidate) continue;
        try {
            return new URL(candidate).origin;
        } catch {
            // Not a URL. Try the next candidate rather than emitting a broken link.
        }
    }
    return "";
}

export function messagesForHook(payload: HookPayload): HookPlan {
    const { user, email_data } = payload;
    const type = email_data.email_action_type;
    const siteUrl = appOrigin(email_data);
    const tokenHash = email_data.token_hash;

    if (!HANDLED.has(type)) return { ok: true, messages: [] };
    if (!siteUrl)
        return {
            ok: false,
            reason: "no usable app origin in the payload (redirect_to and site_url)",
        };

    if (type === "email_change") {
        // Not wired. GoTrue sends both token pairs in this single call and the field names are
        // reversed for backward compatibility (token_hash_new belongs to the CURRENT address,
        // token_hash to the NEW one), so getting it wrong routes a live one-time token to the
        // wrong inbox. claim_membership binds a pending seat on auth.email() and requires only
        // email_confirmed_at, so someone who completes a change to an address they do not
        // control can then claim that address's pending seats in any tenant.
        //
        // Refusing produces a 500, which GoTrue reports as a failed change and the user retries,
        // regenerating both tokens. That is strictly safer than the alternative, and safer than
        // the single wrong-token send this function used to do. Wire it once a real payload has
        // been captured from a local `supabase functions serve` run, which is the only way to
        // confirm user.new_email is populated at runtime.
        return {
            ok: false,
            reason: "email_change routing is not wired yet; refusing rather than routing a token to the wrong address",
        };
    }

    if (!tokenHash) return { ok: false, reason: `no token_hash for ${type}` };
    if (!user.email) return { ok: false, reason: `no recipient for ${type}` };

    const meta = user.user_metadata ?? {};
    const kind = kindForSingleRecipient(type, meta);
    const rendered = renderAuthEmail(kind, {
        siteUrl,
        tokenHash,
        ensembleName: metaString(meta, ensembleKeyFor(kind)),
        invitedByName: metaString(meta, "invited_by_name"),
        displayName: metaString(meta, "display_name"),
    });

    return {
        ok: true,
        messages: [{ to: user.email, ...rendered }],
    };
}

/** Which arrival an invite is. Branch on the positive marker `invite_kind`, never on
 *  `pending_ensemble_name`: SignupForm stamps that key with the signer-up's own typed group
 *  name, and GoTrue refuses an invite only for a CONFIRMED user, so an unconfirmed self-signup
 *  account can still receive an invite while carrying it. Reading it here would render the
 *  director copy to a singer.
 *
 *  Invites sent before invite_kind existed carry no marker and fall to invite_shared, whose
 *  copy is honest for either arrival. */
function kindForSingleRecipient(
    type: string,
    meta: Record<string, unknown>,
): EmailKind {
    if (type !== "invite") return type as EmailKind;
    const inviteKind = meta["invite_kind"];
    if (inviteKind === "director") return "invite_director";
    if (inviteKind === "member") return "invite_member";
    return "invite_shared";
}

/** The director on-ramp names its ensemble in pending_ensemble_name (which /auth/confirm also
 *  reads to seed it); a member seat names its ensemble in invited_ensemble_name, which is
 *  display only and reaches no seed path. */
function ensembleKeyFor(kind: EmailKind): string {
    return kind === "invite_director"
        ? "pending_ensemble_name"
        : "invited_ensemble_name";
}

function metaString(
    meta: Record<string, unknown>,
    key: string,
): string | undefined {
    const value = meta[key];
    return typeof value === "string" && value.trim() ? value : undefined;
}
