-- ============================================================================
-- Row-level security: the auth helpers, table privileges, and every policy.
--
-- Model
--   Isolation is by membership, not by a session variable. A user reaches a row when they
--   hold an active member row in that row's active ensemble. Their tier on that membership
--   decides writes. The app narrows a screen by filtering on ensemble_id; RLS only draws
--   the hard boundary.
--
-- Ordering inside this file is load-bearing in three places.
--   1. The three helper functions come first. Every policy below calls one of them, and a
--      policy expression is parsed at creation time, so the functions must already exist.
--   2. The blanket table grant runs before casting_visible is created. `grant ... on all
--      tables in schema public` includes views, and the view is meant to be select-only for
--      authenticated. Creating it after the blanket grant, then granting select on it
--      explicitly, is what keeps it that way.
--   3. app_user's update privilege is narrowed to two columns after the blanket grant, and
--      invite_rate_event is stripped back to deny-all after it. Both are subtractions from
--      the blanket, so they cannot precede it.
--
-- Ordering against the other files: 001 creates every table this file grants on and guards.
-- 003 through 007 define triggers and RPCs that call these helpers, so they come after.
--
-- Policies are written out one per statement rather than generated by a loop over a table
-- array. The loop was shorter, but five of the policies it produced were later replaced with
-- narrower reads (program, program_item, setlist, setlist_item, setlist_break), so a loop
-- here would have to be followed by a set of overrides, and the final shape of any one table
-- would live in two places. Written out, each policy's live form is one greppable statement
-- that lines up with one line of the catalog. The cost is 34 near-identical statements for
-- the common member-reads-director-writes pattern. On a security surface that is the right
-- trade: this is the file you read to answer "who can see this row".
--
-- Two properties to keep in mind when editing anything below.
--   - Permissive policies are OR'd. Adding a policy to a table can only widen access, never
--     narrow it. To narrow a read you replace the existing policy, you do not add one.
--   - A membership check must gate EVERY branch of a multi-branch read. A bare predicate
--     like `published_at is not null` sitting beside the tenant check under an OR matches
--     rows in every ensemble.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- The auth helpers.
--
-- The recursion trap is why these are SECURITY DEFINER. A policy that guards a row has to
-- read the member table to check membership. The member table needs the same guard, so its
-- policy would read member to decide whether you can read member. That recurses. These
-- functions read membership with RLS turned off inside them, which breaks the cycle. Every
-- policy in this file leans on one of them.
--
-- Hardening that applies to all three: search_path is pinned to `pg_catalog, pg_temp` (not
-- public, and pg_temp last) and every table they touch is schema-qualified, so a caller with
-- temp-object rights cannot shadow a relation these definer functions trust.
--
-- Both membership helpers require the member row to be active AND the ensemble to be active.
-- Without the ensemble check, archiving or suspending a tenant would be cosmetic: every
-- policy built on the tier would keep passing. With it, archiving freezes the tenant
-- transparently, everywhere at once.
-- ----------------------------------------------------------------------------

-- The caller's tier in an ensemble, or null if they are not an active member of it.
create or replace function public.auth_member_tier(p_ensemble uuid)
returns text
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $$
select m.permission_tier
from public.member m
join public.ensemble e on e.id = m.ensemble_id
where m.ensemble_id = p_ensemble
and m.user_id = auth.uid()
and m.status = 'active'
and e.status = 'active'
limit 1;
$$;

-- True when the given member row belongs to the caller. For self-writes.
-- Self-READ does not use this: member_read has its own `user_id = auth.uid()` branch, so a
-- member can still see their own row in an archived tenant even though they cannot write it.
create or replace function public.auth_is_self(p_member uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $$
select exists (
    select 1 from public.member m
    join public.ensemble e on e.id = m.ensemble_id and e.status = 'active'
    where m.id = p_member and m.user_id = auth.uid()
    and m.status = 'active'
);
$$;

-- True when the caller is a platform admin (operator or sales). This gates the /admin surface
-- and the admin-invite path, nothing else. It grants NO cross-tenant data access: no policy in
-- this file references it, so a platform admin still cannot read another ensemble's rows. The
-- flag is set out of band by SQL; no app route writes it. An anonymous caller coalesces to false.
create or replace function public.auth_is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $$
select coalesce(
    (select u.is_platform_admin from public.app_user u where u.id = auth.uid()),
    false
);
$$;

revoke all on function public.auth_is_platform_admin() from public;
grant  execute on function public.auth_is_platform_admin() to authenticated;


-- ----------------------------------------------------------------------------
-- Base-table privileges for the PostgREST roles.
--
-- Migrations run as `postgres`, whose default privileges confer only
-- REFERENCES/TRIGGER/TRUNCATE/MAINTAIN on new tables to the API roles, not read or write
-- (only supabase_admin's default privileges do that). Without this grant an authenticated
-- user hits "permission denied for table" before RLS is ever consulted.
--
-- These grants decide only whether a role may touch a table at all; the policies below decide
-- which rows. A non-director's write matches no policy and touches zero rows. anon is granted
-- nothing here and so reaches no tenant table.
-- ----------------------------------------------------------------------------

grant select, insert, update, delete on all tables in schema public to authenticated;

-- app_user carries is_platform_admin, and app_user_update lets a user update their own row.
-- A blanket table-level UPDATE plus that policy would let anyone PATCH is_platform_admin = true
-- on themselves through PostgREST and self-promote. Column privileges are checked independently
-- of RLS, so pin authenticated's UPDATE to the two self-editable columns. The admin flag is then
-- unwritable by authenticated at all. It is not writable by service_role either, which holds no
-- grant on app_user and cannot even read it, so the only way in is a superuser connection. The app never
-- PATCHes app_user directly (profile edits go through the update_my_profile definer RPC), so this
-- narrows nothing the app relies on.
revoke update on public.app_user from authenticated;
grant  update (email, display_name) on public.app_user to authenticated;

-- invite_rate_event is deny-all: RLS on (below) with no policies, and no grants to authenticated
-- or anon, so PostgREST cannot touch it. The rate-limit definer functions are the only access
-- path. This revoke undoes the blanket grant above for this one table.
revoke all on public.invite_rate_event from authenticated, anon;


-- ----------------------------------------------------------------------------
-- Enable RLS on every table. With RLS on and no policy, a table denies all access, which is
-- exactly what invite_rate_event wants and why the policies for everything else follow
-- immediately.
-- ----------------------------------------------------------------------------

alter table public.app_user            enable row level security;
alter table public.attendance          enable row level security;
alter table public.availability        enable row level security;
alter table public.casting             enable row level security;
alter table public.ensemble            enable row level security;
alter table public.event               enable row level security;
alter table public.event_tag           enable row level security;
alter table public.event_type          enable row level security;
alter table public.event_type_tag      enable row level security;
alter table public.invite_rate_event   enable row level security;
alter table public.member              enable row level security;
alter table public.member_invite       enable row level security;
alter table public.member_voice_part   enable row level security;
alter table public.padding_profile     enable row level security;
alter table public.part                enable row level security;
alter table public.performance_soloist enable row level security;
alter table public.prep_target         enable row level security;
alter table public.program             enable row level security;
alter table public.program_item        enable row level security;
alter table public.rehearsal_item      enable row level security;
alter table public.setlist             enable row level security;
alter table public.setlist_break       enable row level security;
alter table public.setlist_item        enable row level security;
alter table public.song                enable row level security;
alter table public.song_tag            enable row level security;
alter table public.tag                 enable row level security;
alter table public.voice_part          enable row level security;


-- ----------------------------------------------------------------------------
-- The common pattern: any active member reads, the director writes.
-- Covers the curated data and its link tables. A `for all` write policy is USING for the rows
-- an UPDATE or DELETE may target and WITH CHECK for the rows an INSERT or UPDATE may leave
-- behind; both sides are the same predicate here.
-- ----------------------------------------------------------------------------

create policy voice_part_read on public.voice_part
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy voice_part_write on public.voice_part
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy member_voice_part_read on public.member_voice_part
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy member_voice_part_write on public.member_voice_part
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy song_read on public.song
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy song_write on public.song
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy part_read on public.part
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy part_write on public.part
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy padding_profile_read on public.padding_profile
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy padding_profile_write on public.padding_profile
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy event_type_read on public.event_type
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy event_type_write on public.event_type
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy event_read on public.event
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy event_write on public.event
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy tag_read on public.tag
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy tag_write on public.tag
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy song_tag_read on public.song_tag
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy song_tag_write on public.song_tag
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy event_tag_read on public.event_tag
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy event_tag_write on public.event_tag
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy event_type_tag_read on public.event_type_tag
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy event_type_tag_write on public.event_type_tag
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy performance_soloist_read on public.performance_soloist
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy performance_soloist_write on public.performance_soloist
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- rehearsal_item: the agenda for a rehearsal. Same shape as program_item's write side.
create policy rehearsal_item_read on public.rehearsal_item
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy rehearsal_item_write on public.rehearsal_item
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- prep_target: the songs a gig is being prepared for. The director sets the list.
create policy prep_target_read on public.prep_target
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy prep_target_write on public.prep_target
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- attendance: who actually turned up. Unlike availability, which the member owns, attendance
-- is a record the director keeps, so writes are director-only.
create policy attendance_read on public.attendance
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy attendance_write on public.attendance
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');


-- ----------------------------------------------------------------------------
-- The tables that sit apart.
-- ----------------------------------------------------------------------------

-- app_user: self only. In-group display names come from member.display_name, not here.
-- Inserts happen through the auth.users trigger in 003, so there is no insert policy.
create policy app_user_read on public.app_user
for select using (id = auth.uid());
create policy app_user_update on public.app_user
for update using (id = auth.uid()) with check (id = auth.uid());

-- ensemble: members read, the director updates. Creation is the chicken-and-egg case, handled
-- by create_ensemble_seeded in 007, so there is no insert policy. No hard delete; retire a
-- tenant with status = 'archived'.
create policy ensemble_read on public.ensemble
for select using (public.auth_member_tier(id) is not null);
create policy ensemble_update on public.ensemble
for update using (public.auth_member_tier(id) = 'director')
with check (public.auth_member_tier(id) = 'director');

-- member: read the roster of your ensembles, plus your own row anywhere. The second branch is
-- what lets a member see their seat in a tenant whose tier no longer resolves. The director
-- writes the roster. A member edits their own name and range through update_my_profile, not
-- here, so they cannot touch their own tier.
create policy member_read on public.member
for select using (public.auth_member_tier(ensemble_id) is not null or user_id = auth.uid());
create policy member_write on public.member
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- member_invite: director-only read AND write. The invite email and token hash live here
-- precisely so that member_read cannot expose a peer's pending invite address. RLS is the
-- enforcement, not an app-layer projection; a raw PostgREST query gets nothing.
-- The invitee's own view of their invitations comes from definer functions in 007 that read
-- through this policy: list_pending_invitations, accept_invitation, decline_invitation and
-- refresh_pending_invite. Each keys on the caller's own confirmed address rather than an argument.
create policy member_invite_read on public.member_invite
for select using (public.auth_member_tier(ensemble_id) = 'director');
create policy member_invite_write on public.member_invite
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- availability: the member owns the whole row, so a self-write policy is enough. A member
-- writes their own RSVP, the director writes anyone's.
create policy availability_read on public.availability
for select using (public.auth_member_tier(ensemble_id) is not null);
create policy availability_write on public.availability
for all using (public.auth_is_self(member_id) or public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_is_self(member_id) or public.auth_member_tier(ensemble_id) = 'director');


-- ----------------------------------------------------------------------------
-- The narrowed reads: the director's private drafting space, and the member-visible set.
-- ----------------------------------------------------------------------------

-- program / program_item: the playground is the director's private drafting space. The page
-- layer bounces members and the API requires a director, but a plain member could still SELECT
-- these through PostgREST under the common read pattern, exposing the proposed song order and
-- the open/close/keep pins. Director-only read matches the audience the rest of the stack
-- already enforces. Writes were always director-only.
create policy program_read on public.program
for select using (public.auth_member_tier(ensemble_id) = 'director');
create policy program_write on public.program
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy program_item_read on public.program_item
for select using (public.auth_member_tier(ensemble_id) = 'director');
create policy program_item_write on public.program_item
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- setlist: any read still requires active membership of THIS row's ensemble. That is the
-- tenant boundary and it gates every branch. Drop it from one branch and the bare
-- published/performed/share_draft predicate matches rows in every ensemble and leaks across
-- tenants. Within the tenant a director reads all; a member reads a set that is published,
-- performed, or a draft the director chose to share. draft_order and published_order ride this
-- row, so this one policy covers both member read paths with no separate policy.
create policy setlist_read on public.setlist
for select using (
    public.auth_member_tier(ensemble_id) is not null
    and (
        public.auth_member_tier(ensemble_id) = 'director'
        or published_at is not null
        or status = 'performed'
        or share_draft
    )
);
create policy setlist_write on public.setlist
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

-- setlist_item / setlist_break: same tenant guard, then readable when the parent setlist is.
-- The subquery names the parent's gate explicitly rather than leaning on setlist_read composing
-- through. Note the parent gate here is published-or-performed only, deliberately narrower than
-- setlist_read: a shared draft is read from the setlist row's snapshot, never from these child
-- rows, so a member sees no draft item or break.
create policy setlist_item_read on public.setlist_item
for select using (
    public.auth_member_tier(ensemble_id) is not null
    and (
        public.auth_member_tier(ensemble_id) = 'director'
        or exists (
            select 1 from public.setlist s
            where s.ensemble_id = setlist_item.ensemble_id
            and s.id = setlist_item.setlist_id
            and (s.published_at is not null or s.status = 'performed')
        )
    )
);
create policy setlist_item_write on public.setlist_item
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');

create policy setlist_break_read on public.setlist_break
for select using (
    public.auth_member_tier(ensemble_id) is not null
    and (
        public.auth_member_tier(ensemble_id) = 'director'
        or exists (
            select 1 from public.setlist s
            where s.ensemble_id = setlist_break.ensemble_id
            and s.id = setlist_break.setlist_id
            and (s.published_at is not null or s.status = 'performed')
        )
    )
);
create policy setlist_break_write on public.setlist_break
for all using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');


-- ----------------------------------------------------------------------------
-- casting: ownership is per column. The director owns the assignment, is_primary, and their
-- own private assessment; the member owns self_reported_confidence. RLS is row-level, so it
-- cannot split that.
--
-- Writes: the director writes the row here. Members write their own confidence through
-- set_my_confidence (006), never directly.
-- Reads: members have no SELECT policy on the base table and reach castings only through
-- casting_visible, which nulls other people's confidence unless the ensemble is set to
-- 'shared'. That makes 'private' actually hold rather than being a UI nicety.
-- ----------------------------------------------------------------------------

create policy casting_insert on public.casting
for insert with check (public.auth_member_tier(ensemble_id) = 'director');
create policy casting_update on public.casting
for update using (public.auth_member_tier(ensemble_id) = 'director')
with check (public.auth_member_tier(ensemble_id) = 'director');
create policy casting_delete on public.casting
for delete using (public.auth_member_tier(ensemble_id) = 'director');

-- Load-bearing, and easy to mistake for redundancy. A filtered casting write
-- (DELETE or UPDATE ... WHERE part_id in (...)) needs its target rows visible through a SELECT
-- policy, not just the DELETE/UPDATE USING clause. Without this the director's own writes would
-- silently match zero rows. The second reason is plainer: the director owns this data and the
-- view exposes all of it to them anyway.
create policy casting_select_director on public.casting
for select using (public.auth_member_tier(ensemble_id) = 'director');


-- ----------------------------------------------------------------------------
-- casting_visible: the member read path for castings.
--
-- The view runs with its owner's rights and bypasses casting's RLS, so the WHERE clause is the
-- tenant guard and the CASE arms are the confidence guard. security_barrier keeps a
-- caller-supplied predicate from being evaluated ahead of those quals.
--
-- The barrier was measured before it shipped, because a barrier view refuses to push
-- caller quals down unless they are leakproof and the drafter's hottest read goes through here.
-- On the query shape the drafter's castings CTE uses, the ensemble filter reaches the base scan
-- either way, and with the barrier it reaches it as an index condition on idx_casting_ensemble
-- rather than a post-filter. The uncorrelated sub-select becomes an InitPlan evaluated once, so
-- the qual reduces to a leakproof equality that is pushdown-safe. A correlated sub-select would
-- not be, which is what the general warning about barrier views is about. The cost that remains
-- is that genuinely non-pushdown-safe quals now stay outside the view.
-- ----------------------------------------------------------------------------

create view public.casting_visible with (security_barrier = true) as
select
c.id, c.ensemble_id, c.part_id, c.member_id, c.is_primary,
case
when public.auth_is_self(c.member_id)                    then c.self_reported_confidence
when public.auth_member_tier(c.ensemble_id) = 'director' then c.self_reported_confidence
when e.confidence_visibility = 'shared'                  then c.self_reported_confidence
else null
end as self_reported_confidence,
-- The director's private read of each cover, and the date it was confirmed solid. A member
-- never sees the director's assessment of anyone, including themselves. This is the read path
-- the learning tracker and the casting editor use.
case when public.auth_member_tier(c.ensemble_id) = 'director' then c.director_assessed end as director_assessed,
case when public.auth_member_tier(c.ensemble_id) = 'director' then c.learned_at        end as learned_at,
c.created_at, c.updated_at, c.created_by, c.updated_by
from public.casting c
join public.ensemble e on e.id = c.ensemble_id
where public.auth_member_tier(c.ensemble_id) is not null;

-- Members reach castings only through this view. The base-table SELECT privilege from the
-- blanket grant stays in place so casting_select_director and the director's filtered writes
-- can resolve their rows; a member matches no SELECT policy there, so a direct read of casting
-- returns zero rows even with the privilege.
grant select on public.casting_visible to authenticated;
