-- ============================================================================
-- SetWright schema baseline, file 1 of 8: extensions, tables, constraints, indexes.
--
-- This is the compiled data model. It carries the shape the old 64-migration series
-- arrived at, with every later alter-table folded into the create-table it belongs to.
-- Structure only. No functions beyond the one a column default needs, no grants, no
-- RLS, no triggers, no comments on catalog objects. Those are files 2 through 8.
--
-- Ordering, inside this file and against the rest of the set
--   - moddatetime is created first. Nothing here uses it; file 3 hangs the
--     updated_at triggers off it, and an extension is cheap to have early.
--   - gen_public_id() is declared before the tables because six of them take it as
--     a column DEFAULT, and a default must resolve at create-table time. It is the
--     only function in this file, and it lives here for that reason alone.
--   - Tables come in dependency order: identity and tenant root, then people,
--     repertoire, events, tags, sets, then the tables that arrived later.
--   - Constraint-backed indexes are NOT repeated as create index. Every primary key
--     and unique constraint already builds one. Only the 49 indexes below are
--     explicit: the partial uniques the app treats as singletons, the
--     case-insensitive uniques, the public_id lookups, and the foreign-key set.
--   - File 2 enables RLS and grants. Until it runs, these tables are owner-only.
--
-- Conventions
--   - Primary keys are uuid, generated by the database with gen_random_uuid().
--     They are v4, so they are random: id order is NOT creation order. Nothing may
--     order by id expecting insertion sequence. The original header preferred
--     app-layer v7 for index locality; that was never built. Use created_at.
--   - public_id is the one identifier the app mints, and the only one that appears
--     in a URL. The uuid stays the join key everywhere below the routing layer.
--   - All timestamps are timestamptz. created_at / updated_at on every table with a
--     lifecycle. updated_at is maintained by moddatetime triggers in file 3 on 17 of the
--     20 tables that carry it. attendance, prep_target and rehearsal_item have no trigger,
--     so their updated_at never moves off the insert default. Harmless today because all
--     three are written only by full replace, and a trap for the first partial UPDATE.
--   - Provenance: created_by / updated_by reference app_user, on delete set null, so
--     removing a user never breaks the audit trail. app_user, the identity table,
--     carries no provenance of its own. The tables added after the first cut
--     (member_invite, invite_rate_event) carry none either.
--   - Multi-tenancy: every tenant-scoped table carries ensemble_id, and foreign keys
--     between tenant-scoped tables are composite and include it, so the database
--     itself refuses a cross-tenant reference. Belt and suspenders with RLS.
--   - Fixed vocabularies (status, readiness, ...) are text + check. Vocabularies that
--     vary per ensemble (voice parts, tags, event types) are their own tables.
--   - Pitch is a MIDI integer, middle C = 60. Key is fifths (-7..+7) plus mode.
--     Durations are seconds. The conversions live in core/src/pitch.ts, nowhere else.
--   - Reserved-word renames: app_user (user), ensemble (group), setlist (set).
--
-- On delete policy
--   - Child rows and link tables cascade from their owning parent.
--   - Optional config references (event->type, event->padding, type->padding) set
--     null, and must name the column so a composite set-null does not try to null
--     ensemble_id.
--   - A voice part cannot be deleted while a chart still calls for it: part ->
--     voice_part is NO ACTION.
--   - Provenance sets null. References to ensemble are NO ACTION; retire a tenant
--     with status = 'archived' rather than deleting it.
--   - performance_soloist is the deliberate exception. It keeps no FK to part,
--     song, or member, because history must not depend on the present.
--
-- app_user depends on Supabase's auth.users. Outside Supabase, point it at your own
-- identity table.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Extensions
-- ----------------------------------------------------------------------------

-- moddatetime supplies the updated_at trigger function. File 3 attaches it.
create extension if not exists moddatetime;


-- ----------------------------------------------------------------------------
-- The URL token generator
-- ----------------------------------------------------------------------------

-- base64url of 16 random bytes with padding stripped, so exactly 22 chars matching
-- ^[A-Za-z0-9_-]{22}$. The app-layer validator and a matching generator live in
-- apps/web/lib/publicId.ts; this is the database side. The bytes come from
-- gen_random_uuid(), built in on PG13+, so no extension is needed. That is 122 bits:
-- unguessable and collision-free at any real scale. RLS still draws tenancy, so the
-- token is an identifier, not a secret.
--
-- Volatile on purpose, which is the sql default. A non-volatile default would let
-- Postgres reuse one value across an add-column backfill and the unique indexes
-- below would fail.
create or replace function public.gen_public_id()
returns text
language sql
volatile
set search_path = pg_catalog, pg_temp
as $$
select rtrim(translate(encode(uuid_send(gen_random_uuid()), 'base64'), '+/', '-_'), '=');
$$;


-- ----------------------------------------------------------------------------
-- Identity (global) and tenant root
-- ----------------------------------------------------------------------------

-- One row per human, 1:1 with Supabase auth.users. The global identity.
create table app_user (
    id                uuid primary key references auth.users(id) on delete cascade,
    email             text,                      -- convenience mirror; auth is canonical
    display_name      text,                      -- the person's own name
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    -- Set out of band by SQL only. No app route writes it, because an endpoint that
    -- grants admin is a privilege-escalation target. It authorizes the /admin surface
    -- and nothing else: no RLS policy reads it, so a platform admin still cannot see
    -- another ensemble's rows. File 2 pins authenticated's UPDATE to the two
    -- self-editable columns so a user cannot PATCH this onto themselves.
    is_platform_admin boolean not null default false,
    -- Founding a new ensemble costs a credit, granted only by a platform admin. A
    -- plain member has none, so create_ensemble_seeded refuses them even though the
    -- RPC is directly callable.
    founding_credits  int not null default 0
);

-- The tenant. Every tenant-scoped row references this.
create table ensemble (
    id          uuid primary key default gen_random_uuid(),
    name        text not null,
    slug        text unique,                     -- future tenant-addressable routing
    timezone    text not null default 'America/New_York',  -- IANA; anchors date math
    status      text not null default 'active'
    check (status in ('active','suspended','archived')),
    -- Peer visibility of casting.self_reported_confidence. 'member_choice' arrives
    -- later with the per-member toggle; kept out of the check until then, to fail loud.
    confidence_visibility text not null default 'private'
    check (confidence_visibility in ('private','shared')),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,
    public_id   text not null default public.gen_public_id()
);


-- ----------------------------------------------------------------------------
-- People
-- ----------------------------------------------------------------------------

-- A singer within one ensemble. Membership + voice profile + role. user_id is null
-- until the person claims the seat; the pending invite itself lives in member_invite,
-- not here, so a peer cannot read the address it was sent to.
create table member (
    id               uuid primary key default gen_random_uuid(),
    ensemble_id      uuid not null references ensemble(id),
    user_id          uuid references app_user(id) on delete set null,
    display_name     text not null,
    permission_tier  text not null default 'member'
    check (permission_tier in ('member','section_leader','director')),
    is_singing       boolean not null default true,  -- false = active member with platform
    -- access who is not pulled into the
    -- singing pool (conductor, manager)
    vocal_range_low  smallint,                   -- MIDI; advisory, not the coverage gate
    vocal_range_high smallint,                   -- MIDI
    status           text not null default 'active'
    check (status in ('active','inactive')),  -- 'inactive' = left the group
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    created_by       uuid references app_user(id) on delete set null,
    updated_by       uuid references app_user(id) on delete set null,
    public_id        text not null default public.gen_public_id(),

    unique (ensemble_id, id),
    unique (ensemble_id, user_id),              -- one membership per user per ensemble
    check (vocal_range_low is null or vocal_range_high is null
        or vocal_range_low <= vocal_range_high)
);

-- The ensemble's section vocabulary: S1, A2, Bass, VP, ... Tenant-defined.
create table voice_part (
    id           uuid primary key default gen_random_uuid(),
    ensemble_id  uuid not null references ensemble(id),
    label        text not null,                  -- 'S2', 'Tenor 1', 'VP'
    sort_order   smallint not null default 0,
    is_pitched   boolean not null default true,  -- false for VP / percussion
    nominal_low  smallint,                       -- section's typical range, MIDI, advisory
    nominal_high smallint,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),
    created_by   uuid references app_user(id) on delete set null,
    updated_by   uuid references app_user(id) on delete set null,

    unique (ensemble_id, id),
    check (nominal_low is null or nominal_high is null or nominal_low <= nominal_high)
);

-- Section labels are unique case-insensitively: the app treats 'Bass' and 'bass'
-- as the same section, so enforce that rather than a bare case-sensitive unique.
create unique index voice_part_label_ci on voice_part (ensemble_id, lower(label));

-- Which sections a member can cover, one marked home. Drives section coverage and
-- the casting screen's eligibility.
create table member_voice_part (
    ensemble_id        uuid not null references ensemble(id),
    member_id          uuid not null,
    voice_part_id      uuid not null,
    is_primary_section boolean not null default false,  -- the member's home section
    created_at         timestamptz not null default now(),

    primary key (member_id, voice_part_id),
    foreign key (ensemble_id, member_id)     references member(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, voice_part_id) references voice_part(ensemble_id, id) on delete cascade
);

create unique index member_one_primary_section
on member_voice_part (member_id) where (is_primary_section);


-- ----------------------------------------------------------------------------
-- Repertoire
-- ----------------------------------------------------------------------------

-- A chart. Key and tempo carry start/end values for transition and arc logic.
create table song (
    id                  uuid primary key default gen_random_uuid(),
    ensemble_id         uuid not null references ensemble(id),
    title               text not null,
    arranger            text,
    chart_ref           text,                    -- URL or location of the music

    start_key_fifths    smallint,                -- opening key signature, -7..+7; null = no set key
    start_key_mode      text check (start_key_mode in ('major','minor')),
    end_key_fifths      smallint,                -- closing key if it modulates; null = ends as it started
    end_key_mode        text check (end_key_mode in ('major','minor')),

    start_tempo_bpm     smallint,                -- opening tempo; null = free / rubato
    end_tempo_bpm       smallint,                -- closing tempo if it changes; null = constant

    start_pitch         text,                    -- pitch to blow before the song, a pitch class like 'C#' or 'Eb'; null = derive from the start key

    duration_seconds    integer,                 -- chart length; event padding applied later
    is_explicit         boolean not null default false,  -- content rating; hard-gated by event policy
    intensity           smallint,                -- director-rated felt energy, 1..5, by peak impact; null = unrated. Independent of tempo and readiness; drives the sequencer's arc and anti-flatline terms.

    assessed_readiness  text not null default 'learning'
    check (assessed_readiness in
    ('performance-ready','needs-polish','learning','dormant')),
    book_status         text not null default 'on-book'
    check (book_status in ('off-book','on-book')),
    last_rehearsed      date,
    last_performed      date,                     -- stamped when a setlist is marked performed
    status              text not null default 'active'
    check (status in ('active','archived')),
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    created_by          uuid references app_user(id) on delete set null,
    updated_by          uuid references app_user(id) on delete set null,
    -- A cappella is the default, so this mirrors is_explicit and defaults false. The
    -- event-side flag defaults the other way.
    uses_accompaniment  boolean not null default false,
    public_id           text not null default public.gen_public_id(),

    unique (ensemble_id, id),
    check ((start_key_fifths is null) = (start_key_mode is null)),
    check ((end_key_fifths   is null) = (end_key_mode   is null)),
    check (start_key_fifths is null or start_key_fifths between -7 and 7),
    check (end_key_fifths   is null or end_key_fifths   between -7 and 7),
    check (end_key_fifths is null or start_key_fifths is not null),
    check (start_tempo_bpm is null or start_tempo_bpm > 0),
    check (end_tempo_bpm   is null or end_tempo_bpm   > 0),
    check (end_tempo_bpm is null or start_tempo_bpm is not null),
    check (duration_seconds is null or duration_seconds > 0),
    check (intensity is null or intensity between 1 and 5),
    check (start_pitch is null or start_pitch ~ '^[A-G](#|b)?$')
);

-- One line the chart calls for. A section line names its voice part (VP included);
-- a solo names none.
create table part (
    id            uuid primary key default gen_random_uuid(),
    ensemble_id   uuid not null references ensemble(id),
    song_id       uuid not null,
    voice_part_id uuid,                           -- the section this line needs; null for a solo
    is_solo       boolean not null default false,
    label         text,                           -- display name within the song: 'Descant', 'Solo 2'
    is_required   boolean not null default true,  -- false parts degrade, they don't gate
    count_needed  smallint not null default 1,    -- minimum singers for this line to count as covered
    range_low     smallint,                       -- specific demand of this line, MIDI; mainly solos
    range_high    smallint,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    created_by    uuid references app_user(id) on delete set null,
    updated_by    uuid references app_user(id) on delete set null,
    -- Display only. The drafter is order-agnostic and the hydration carries no order
    -- by, so no gate reads this. There is no reorder RPC either: the client already
    -- sends parts in visual order and both write paths stamp the array index.
    sort_order    smallint not null default 0,

    unique (ensemble_id, id),
    unique (ensemble_id, song_id, id),  -- backs nothing now; see the note above performance_soloist
    foreign key (ensemble_id, song_id)
    references song(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, voice_part_id)
    references voice_part(ensemble_id, id),
    check ((is_solo and voice_part_id is null)
        or (not is_solo and voice_part_id is not null)),
    check (count_needed > 0),
    check (range_low is null or range_high is null or range_low <= range_high)
);

-- Who is assigned to a part, and how solid they feel. is_primary marks the lead on a
-- featured part; section parts leave it false.
create table casting (
    id                       uuid primary key default gen_random_uuid(),
    ensemble_id              uuid not null references ensemble(id),
    part_id                  uuid not null,
    member_id                uuid not null,
    is_primary               boolean not null default false,
    self_reported_confidence text
    check (self_reported_confidence in ('solid','shaky','learning')),
    director_assessed        text
    check (director_assessed in ('solid','shaky','learning')),  -- the director's read of this cover, distinct from the member's self-report
    learned_at               timestamptz,             -- date the cover was confirmed solid; null while not solid
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now(),
    created_by               uuid references app_user(id) on delete set null,
    updated_by               uuid references app_user(id) on delete set null,

    unique (member_id, part_id),
    foreign key (ensemble_id, part_id)
    references part(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, member_id)
    references member(ensemble_id, id) on delete cascade
);

create unique index casting_one_lead_per_part
on casting (part_id) where (is_primary);


-- ----------------------------------------------------------------------------
-- Events and their config
-- ----------------------------------------------------------------------------

-- Reusable time-overhead profile. Several event types can share one.
create table padding_profile (
    id               uuid primary key default gen_random_uuid(),
    ensemble_id      uuid not null references ensemble(id),
    name             text not null,              -- 'Concert', 'Church service', 'Competition'
    per_song_seconds integer not null default 0, -- applause, transition, brief patter, per song
    per_set_seconds  integer not null default 0, -- one-time overhead: intro, outro, MC
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    created_by       uuid references app_user(id) on delete set null,
    updated_by       uuid references app_user(id) on delete set null,

    unique (ensemble_id, id),
    unique (ensemble_id, name),
    check (per_song_seconds >= 0),
    check (per_set_seconds  >= 0)
);

-- The kind of gig. Carries the type-level policy defaults. Tenant-defined.
create table event_type (
    id                      uuid primary key default gen_random_uuid(),
    ensemble_id             uuid not null references ensemble(id),
    name                    text not null,
    sort_order              smallint not null default 0,
    padding_profile_id      uuid,                -- default padding for this type
    default_allows_on_book  boolean not null default false,
    default_allows_explicit boolean not null default false,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    created_by              uuid references app_user(id) on delete set null,
    updated_by              uuid references app_user(id) on delete set null,
    -- Defaults true, unlike the explicit flags: accompaniment is permitted until a
    -- director turns it off.
    default_allows_accompaniment boolean not null default true,

    unique (ensemble_id, id),
    unique (ensemble_id, name),
    -- Composite FK, but SET NULL must touch ONLY padding_profile_id: a bare SET NULL on
    -- a multi-column FK also nulls ensemble_id (NOT NULL) and fails the delete. The
    -- column-list form (PostgreSQL 15+) clears just the optional reference.
    foreign key (ensemble_id, padding_profile_id)
    references padding_profile(ensemble_id, id) on delete set null (padding_profile_id)
);

-- A booking. Owns its resolved policy + padding, snapshotted from its event_type at
-- create (or "apply defaults"); editing the type afterwards does NOT change existing
-- events. event_type_id is provenance/grouping only.
create table event (
    id                      uuid primary key default gen_random_uuid(),
    ensemble_id             uuid not null references ensemble(id),
    event_type_id           uuid,                -- provenance/grouping; null = untyped
    name                    text not null,
    event_date              date,                -- null = TBD
    venue                   text,
    target_duration_seconds integer,             -- set-length goal, in seconds
    allows_on_book          boolean not null default false,
    allows_explicit         boolean not null default false,
    per_song_seconds        integer not null default 0, -- snapshotted padding: per-song overhead/gap
    per_set_seconds         integer not null default 0, -- snapshotted padding: one-time overhead
    status                  text not null default 'planned'
    check (status in ('planned','cancelled')),
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    created_by              uuid references app_user(id) on delete set null,
    updated_by              uuid references app_user(id) on delete set null,
    allows_accompaniment    boolean not null default true,
    -- A hard ceiling, distinct from the soft target. core honors the tighter of the
    -- two and reports the overshoot a trim cannot pull (pins, forced keeps, segues).
    max_duration_seconds    integer,
    -- A rehearsal reuses the whole event + availability + RSVP machinery. Set at
    -- create and never edited: a gig stays a gig. This is a calendar discriminator,
    -- not a drafter signal; the hydration and the funnel never read it.
    kind                    text not null default 'gig'
    check (kind in ('gig','rehearsal')),
    public_id               text not null default public.gen_public_id(),

    unique (ensemble_id, id),
    -- SET NULL only event_type_id (see padding_profile note above): a bare composite
    -- SET NULL would also null ensemble_id (NOT NULL) and fail deleting an event type.
    foreign key (ensemble_id, event_type_id)
    references event_type(ensemble_id, id) on delete set null (event_type_id),
    check (target_duration_seconds is null or target_duration_seconds > 0),
    check (per_song_seconds >= 0),
    check (per_set_seconds  >= 0),
    check (max_duration_seconds is null
        or (max_duration_seconds > 0
            and (target_duration_seconds is null
                or max_duration_seconds >= target_duration_seconds)))
);


-- ----------------------------------------------------------------------------
-- Tags and appropriateness
-- ----------------------------------------------------------------------------

-- Open style/genre/mood/occasion vocabulary. Tenant-defined.
create table tag (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    name        text not null,                   -- 'gospel', 'holiday', 'ballad', 'uptempo'
    category    text                             -- read in one place only: the sequencer treats
    -- mood, groove and genre as feel and diversifies adjacency on them. occasion and content have
    -- no behaviour anywhere and are labels. Content gating is song.is_explicit against
    -- event.allows_explicit, nothing to do with this column.
    check (category is null or category in ('mood','groove','genre','occasion','content')),
    sort_order  smallint not null default 0,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (ensemble_id, id)
);

-- Tag names are unique case-insensitively: the app treats 'Gospel' and 'gospel'
-- as the same tag, matching the editor's duplicate guard.
create unique index tag_name_ci on tag (ensemble_id, lower(name));

-- A song's tags.
create table song_tag (
    ensemble_id uuid not null references ensemble(id),
    song_id     uuid not null,
    tag_id      uuid not null,
    created_at  timestamptz not null default now(),

    primary key (song_id, tag_id),
    foreign key (ensemble_id, song_id) references song(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, tag_id)  references tag(ensemble_id, id)  on delete cascade
);

-- Per-event style steering. 'require' is a set-level mandate enforced in core (the
-- drafted set must carry at least one song with each required tag); the database only
-- persists the effect. For a tag named more than once, exclude wins, then require,
-- then prefer.
create table event_tag (
    ensemble_id uuid not null references ensemble(id),
    event_id    uuid not null,
    tag_id      uuid not null,
    effect      text not null default 'prefer'
    check (effect in ('prefer','exclude','require')),
    created_at  timestamptz not null default now(),

    primary key (event_id, tag_id),
    foreign key (ensemble_id, event_id) references event(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, tag_id)   references tag(ensemble_id, id)   on delete cascade
);

-- Per-type tag rules, mainly exclusions. A prefill, not a constraint. Nothing server-side reads
-- this table when an event is saved or drafted: save_event builds event_tag from its own arguments
-- alone. The event form copies these onto a new event on the first type pick, or on demand from the
-- Apply button, and every copied tag is editable afterwards. Changing an existing event's type, an
-- import, or a seed applies none of them.
create table event_type_tag (
    ensemble_id   uuid not null references ensemble(id),
    event_type_id uuid not null,
    tag_id        uuid not null,
    effect        text not null default 'prefer'
    check (effect in ('prefer','exclude','require')),
    created_at    timestamptz not null default now(),

    primary key (event_type_id, tag_id),
    foreign key (ensemble_id, event_type_id) references event_type(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, tag_id)        references tag(ensemble_id, id)        on delete cascade
);


-- ----------------------------------------------------------------------------
-- Availability and sets
-- ----------------------------------------------------------------------------

-- Self-reported attendance. A missing row means no response, distinct from 'out'.
create table availability (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    member_id   uuid not null,
    event_id    uuid not null,
    status      text not null check (status in ('in','out','tentative')),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (member_id, event_id),
    foreign key (ensemble_id, member_id) references member(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, event_id)  references event(ensemble_id, id)  on delete cascade
);

-- A reusable, hand-built program, not tied to an event. The director arranges it
-- with the sequencer and seam logic alone (no availability, no feasibility), then
-- instantiates it into event setlists. Reached from its own menu. Deletable only
-- while no setlist references it (see setlist.program_id).
create table program (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    name        text not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,
    public_id   text not null default public.gen_public_id(),

    unique (ensemble_id, id)
);

-- A song's place in a program: ordered, with an optional opener/closer anchor.
-- Leaner than setlist_item: a program holds only chosen songs (no exclude) and
-- only the two end anchors (keep is a draft-fill concept, not an arrangement one).
create table program_item (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    program_id  uuid not null,
    song_id     uuid not null,
    position    smallint not null,               -- order in the program
    pin         text check (pin in ('open','close')),  -- end anchor; null = interior
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (program_id, song_id),
    foreign key (ensemble_id, program_id) references program(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, song_id)    references song(ensemble_id, id)    on delete cascade
);

-- At most one opener and one closer per program. The app treats these as
-- singletons; this makes the contract match (same shape as casting_one_lead_per_part).
create unique index program_one_open
on program_item (program_id) where (pin = 'open');
create unique index program_one_close
on program_item (program_id) where (pin = 'close');

-- A draft or performed set for an event. Multiple per event are allowed. A set may
-- record the program it was instantiated from (program_id), which also pins that
-- program against deletion while the set lives.
--
-- Three jsonb order columns, and they are not interchangeable:
--   arranged_order  the order the DIRECTOR set by hand. Advisory: the drafter still
--                   decides membership, this only overrides sequence. A redraft
--                   clears it back to null. No constraint, because loadSetlist
--                   reconciles a stale or partial list defensively.
--   draft_order     the snapshot a member sees while share_draft is on. Kept fresh on
--                   every order change. It exists so a member never runs the drafter,
--                   which would expose the whole event pool.
--   published_order the order members read for a published set. Paired with published_at by
--                   check constraint, both null or both set. Not frozen at publish despite the
--                   name: the app rewrites it, and draft_order with it, on every order-changing
--                   edit until the set is performed.
create table setlist (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    event_id    uuid not null,
    program_id  uuid,                            -- the program this set came from, if any
    name        text,                            -- 'Set 1', 'Draft B'; optional
    status      text not null default 'draft'
    check (status in ('draft','final','performed')),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,
    -- Durable, frozen at perform time. Reads used to derive this from event.event_date,
    -- so editing an event later silently rewrote past performances.
    performed_date     date,
    published_at       timestamptz,   -- the member-visibility gate for a finished set
    published_order    jsonb,         -- { songIds, transitions, breaks }
    -- Frozen song metadata plus event name and padding, captured by the app layer at
    -- perform time. Without it a performed sheet re-read live song and event rows, so
    -- editing a song after a gig rewrote history. Null for sets performed before this
    -- existed; those fall back to live reads.
    performed_snapshot jsonb,
    public_id          text not null default public.gen_public_id(),
    share_draft        boolean not null default false,  -- opt-in, reversible member preview
    draft_order        jsonb,
    arranged_order     jsonb,

    unique (ensemble_id, id),
    foreign key (ensemble_id, event_id)   references event(ensemble_id, id)   on delete cascade,
    foreign key (ensemble_id, program_id) references program(ensemble_id, id) on delete restrict,
    -- Both null (unpublished) or both set (published). Nothing in between.
    constraint setlist_published_pair
    check ((published_at is null) = (published_order is null)),
    -- Defence in depth against any path that flips status without a date.
    -- perform_setlist always sets both in one update.
    constraint setlist_performed_has_date
    check (status <> 'performed' or performed_date is not null)
);

-- A song's relationship to a set: placed, locked, or barred. One table, three states.
create table setlist_item (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    setlist_id  uuid not null,
    song_id     uuid not null,
    position    smallint,                        -- order in the set; null when barred
    pin         text check (pin in ('keep','open','close')),  -- lock; null = drafter may move or drop
    is_excluded boolean not null default false,  -- barred from this set; drafter fills around it
    note        text,                            -- director's transition / staging annotation for this item
    transition_seconds smallint                  -- segue: the gap LEAVING this item; null = event per-song default, 0 = attacca
    check (transition_seconds is null or transition_seconds >= 0),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (setlist_id, song_id),
    foreign key (ensemble_id, setlist_id) references setlist(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, song_id)    references song(ensemble_id, id)    on delete cascade,
    check ( (is_excluded and position is null and pin is null)
        or (not is_excluded and position is not null) )
);

-- A break in a setlist's running order: an intermission or extended patter spot. It
-- holds clock time but takes no stage slot, and it is ORDINAL: it sits after the
-- k-th song (after_position), splitting the set into segments the drafter sequences
-- independently (a hard flow-reset). At most one break per ordinal slot.
create table setlist_break (
    id             uuid primary key default gen_random_uuid(),
    ensemble_id    uuid not null references ensemble(id),
    setlist_id     uuid not null,
    label          text not null,
    duration_seconds integer  not null check (duration_seconds >= 0),
    after_position smallint not null check (after_position >= 1),  -- after the k-th song
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    created_by     uuid references app_user(id) on delete set null,
    updated_by     uuid references app_user(id) on delete set null,

    unique (setlist_id, after_position),  -- one break per ordinal slot
    foreign key (ensemble_id, setlist_id) references setlist(ensemble_id, id) on delete cascade
);

-- Who actually soloed at a performance, snapshotted when a set is marked performed,
-- so the record stays true even if the casting changes later. Feeds soloist equity
-- over time. One soloist per part per performance.
--
-- The display fields are denormalized on purpose and there is NO foreign key to part,
-- song, or member. Those FKs cascaded, so a routine chart edit (which deletes and
-- reinserts parts) or removing a member silently erased that member's historical solo
-- appearance. A live probe confirmed it. History must not depend on the present.
-- The setlist FK stays, and a performed setlist is itself protected by the
-- immutability guards in file 3. The ensemble FK stays too, but note what it does: like all 23
-- ensemble references in this schema it is no-action, so it blocks a tenant delete rather than
-- cascading through one. There is no delete-based teardown path here; retiring a tenant is
-- ensemble.status = 'archived'.
create table performance_soloist (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    setlist_id  uuid not null,
    song_id     uuid not null,
    part_id     uuid not null,
    member_id   uuid not null,
    created_at  timestamptz not null default now(),
    song_title          text not null,
    part_label          text not null,
    member_display_name text not null,

    unique (setlist_id, part_id),
    foreign key (ensemble_id, setlist_id) references setlist(ensemble_id, id) on delete cascade
);


-- ----------------------------------------------------------------------------
-- Rehearsals
-- ----------------------------------------------------------------------------

-- A rehearsal's agenda: an ordered, editable list of songs to run, each with a reason
-- and an optional director note. A sibling of program_item and setlist_item, child of
-- event. Only a rehearsal carries one; a gig's plan is its setlist. The suggestions
-- that seed it are computed in the web layer from signals that already exist, so this
-- table only stores the director's curated result. Nothing reads it as a drafter signal.
create table rehearsal_item (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    event_id    uuid not null,
    song_id     uuid not null,
    position    smallint not null,               -- order in the agenda
    reason      text,                            -- 'coverage-risk' | 'learning-gap' | 'stale' | 'upcoming-gig' | null (director pick)
    note        text,                            -- director's rehearsal note for this song
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (event_id, song_id),
    foreign key (ensemble_id, event_id) references event(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, song_id)  references song(ensemble_id, id)  on delete cascade
);

-- Recorded attendance, distinct from RSVP intent. availability answers "who plans to
-- come"; this answers "who showed". A separate table so an attendance value never
-- overwrites an RSVP. A missing row means not recorded, matching availability's
-- "no row = no response".
create table attendance (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    member_id   uuid not null,
    event_id    uuid not null,
    present     boolean not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (member_id, event_id),
    foreign key (ensemble_id, member_id) references member(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, event_id)  references event(ensemble_id, id)  on delete cascade
);

-- An explicit commitment: have this song ready for that gig. The gig's event_date is
-- the deadline, and this edge drives the "behind schedule" view. Nothing modeled it
-- before: setlist is the performed output and an event_tag prefer only steers a draft
-- softly, neither says "we are learning X for show Y". Unordered, gigs only, because
-- a rehearsal is the preparation rather than a thing to prepare for.
create table prep_target (
    id          uuid primary key default gen_random_uuid(),
    ensemble_id uuid not null references ensemble(id),
    event_id    uuid not null,
    song_id     uuid not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    created_by  uuid references app_user(id) on delete set null,
    updated_by  uuid references app_user(id) on delete set null,

    unique (event_id, song_id),
    foreign key (ensemble_id, event_id) references event(ensemble_id, id) on delete cascade,
    foreign key (ensemble_id, song_id)  references song(ensemble_id, id)  on delete cascade
);


-- ----------------------------------------------------------------------------
-- Invitations
-- ----------------------------------------------------------------------------

-- Director-only pending-invite state, one row per unclaimed seat, deleted when the
-- seat is claimed or its status changes. It is a side table because these fields used
-- to sit on member, where any active member could SELECT a peer's invite address and
-- token hash straight through PostgREST. RLS is row-level, so app-layer masking did
-- not stop it. Moving the columns here makes RLS the enforcement.
create table member_invite (
    ensemble_id       uuid not null,
    member_id         uuid not null primary key,
    invite_email      text not null,
    invited_at        timestamptz not null default now(),
    -- SHA-256 of the token delivered to the invited inbox. A confirmed email alone is
    -- not proof of inbox control (public signup auto-confirms), so the claim requires
    -- the raw token. The roster only ever sees this hash.
    invite_token_hash text,
    -- The anchor the unauthenticated resend path cannot move. invited_at renews, so
    -- without this a request every fortnight from anyone who knows the address kept a
    -- seat bindable forever. Never written after insert.
    first_invited_at  timestamptz not null default now(),
    -- Set when the invitee refuses. The row stays so the roster can show the director
    -- it was declined, and nothing re-offers it.
    declined_at       timestamptz,

    foreign key (ensemble_id, member_id) references member(ensemble_id, id) on delete cascade
);

-- One invite row per email per ensemble, pending or declined alike. The app pre-checks
-- member_invite for the same address on a different seat and returns a friendly duplicate
-- message; this index is the backstop when it does not. The index has no partial predicate, and
-- that is deliberate rather than an oversight now that declined rows persist: a declined row keeps
-- occupying the address slot. Every consumer filters declined_at is null. Removing the seat
-- deletes the row and frees the slot.
create unique index member_invite_one_per_email
on member_invite (ensemble_id, lower(invite_email));

-- The rate-limit ledger for the three invite surfaces. In-memory limiting does not
-- hold on Fluid Compute (per-instance, resets on cold start), so the counter lives in
-- Postgres behind SECURITY DEFINER functions. File 2 leaves this table deny-all: RLS
-- on, no policies, no grants. The definer functions are the only access path.
create table invite_rate_event (
    id         bigint generated always as identity primary key,
    subject    text not null,   -- the rate key: an actor's auth.uid()::text, or a normalized email
    kind       text not null,   -- 'director_invite' | 'member_invite' | 'resend'
    created_at timestamptz not null default now()
);

create index invite_rate_event_lookup on invite_rate_event (subject, kind, created_at);
-- Supports the opportunistic global GC in consume_kind, a delete keyed only on created_at.
create index invite_rate_event_created on invite_rate_event (created_at);


-- ----------------------------------------------------------------------------
-- Indexes on foreign-key columns and the tenant key on link tables.
-- A set tied to expected query paths, not a final strategy. Primary keys and unique
-- constraints already build their own; nothing here duplicates one.
-- ----------------------------------------------------------------------------

create index idx_member_user                  on member (user_id);

create index idx_mvp_voice_part               on member_voice_part (voice_part_id);
create index idx_mvp_ensemble                 on member_voice_part (ensemble_id);

create index idx_part_song                    on part (song_id);
create index idx_part_voice_part              on part (voice_part_id);

create index idx_casting_part                 on casting (part_id);
create index idx_casting_ensemble             on casting (ensemble_id);

create index idx_event_type                   on event (event_type_id);

create index idx_song_tag_tag                 on song_tag (tag_id);
create index idx_song_tag_ensemble            on song_tag (ensemble_id);

create index idx_event_tag_tag                on event_tag (tag_id);
create index idx_event_tag_ensemble           on event_tag (ensemble_id);

create index idx_event_type_tag_tag           on event_type_tag (tag_id);
create index idx_event_type_tag_ensemble      on event_type_tag (ensemble_id);

create index idx_availability_event           on availability (event_id);
create index idx_availability_ensemble        on availability (ensemble_id);

create index idx_program_item_song            on program_item (song_id);
create index idx_program_item_ensemble        on program_item (ensemble_id);

create index idx_setlist_event                on setlist (event_id);
create index idx_setlist_program              on setlist (program_id);

create index idx_setlist_item_song            on setlist_item (song_id);
create index idx_setlist_item_ensemble        on setlist_item (ensemble_id);

create index idx_setlist_break_setlist        on setlist_break (setlist_id);
create index idx_setlist_break_ensemble       on setlist_break (ensemble_id);

create index idx_perf_soloist_song            on performance_soloist (song_id);
create index idx_perf_soloist_part            on performance_soloist (part_id);
create index idx_perf_soloist_member          on performance_soloist (member_id);
create index idx_perf_soloist_ensemble        on performance_soloist (ensemble_id);

create index idx_rehearsal_item_event         on rehearsal_item (event_id);
create index idx_rehearsal_item_ensemble      on rehearsal_item (ensemble_id);

create index idx_attendance_event             on attendance (event_id);
create index idx_attendance_ensemble          on attendance (ensemble_id);

create index idx_prep_target_event            on prep_target (event_id);
create index idx_prep_target_ensemble         on prep_target (ensemble_id);

-- public_id lookups. A unique b-tree also serves the token-to-row point lookups the
-- routing layer runs (resolvePublicId, the proxy's ensemble resolution), so there is
-- no separate lookup index.
create unique index idx_ensemble_public_id    on ensemble (public_id);
create unique index idx_song_public_id        on song (public_id);
create unique index idx_member_public_id      on member (public_id);
create unique index idx_setlist_public_id     on setlist (public_id);
create unique index idx_event_public_id       on event (public_id);
create unique index idx_program_public_id     on program (public_id);
